volumes:
  postgres_data:

networks:
  my-network:

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "audit-log:1:1,api-log:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - my-network

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres-products:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ms-products:
    build: ./ms-products
    environment:
      POSTGRES_DB_HOST: postgres-products
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: postgres
      POSTGRES_DB_NAME: products
      POSTGRES_DB_SYNCHRONIZE: true
      PRODUCTS_DEFAULT_CURRENCY: DOP
      EXCHANGE_RATE_API_URL: https://v6.exchangerate-api.com/v6/
      EXCHANGE_RATE_API_KEY: 00d7d10e5b62944a6091a4b9
      EVENT_STREAMING_BROKERS: kafka:9092
      EVENT_STREAMING_CLIENT_ID: ms-products-client
      EVENT_STREAMING_CONSUMER_GROUP_ID: ms-products-group
      CACHE_URL: redis://redis:6379
      JWT_SECRET: my_super_secret_jwt_key
    depends_on:
      - redis
      - postgres-products
    ports:
      - "3000:3000"

  # postgres-stocks:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: stocks
  #   ports:
  #     - "5433:5432"

  # ms-stocks:
  #   build: ./ms-stocks
  #   depends_on:
  #     - kafka
  #     - redis
  #     - postgres-stocks

  # auth:
  #   build: ./auth